# Development Environment Configuration
# Overrides base config.yaml for development

environment: development
log_level: debug

# Development server settings
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 60
  write_timeout: 60
  idle_timeout: 120

# Development database settings
database:
  host: localhost
  port: 5432
  username: dev_user
  password: dev_password
  database: ai_gateway_dev
  ssl_mode: disable
  max_open_conns: 10
  max_idle_conns: 2

# Development Redis settings
redis:
  host: localhost
  port: 6379
  password: ""
  database: 1
  pool_size: 5

# Development provider settings (less strict rate limits)
providers:
  openai:
    timeout: 120s
    max_retries: 5
    rate_limit:
      enabled: false  # Disabled for development
  anthropic:
    timeout: 120s
    max_retries: 5
    rate_limit:
      enabled: false  # Disabled for development

# Development proxy settings
proxy:
  enabled: false  # Disabled for development

# Development security settings (less strict)
security:
  jwt_secret: "dev-secret-key-not-for-production-12345678901234567890"
  jwt_expiry: 48h
  cors_enabled: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://localhost:8080"
  tls_min_version: "1.2"

# Development cache settings
cache:
  enabled: true
  default_ttl: 5m  # Shorter TTL for development
  max_size: "10MB"

# Development rate limiting (more permissive)
rate_limit:
  enabled: false
  requests_per_min: 1000
  burst_size: 500

# Development monitoring
monitoring:
  enabled: true
  metrics_port: 9090

# Development timeouts (longer for debugging)
timeouts:
  default_request_timeout: "60s"
  chat_completion_timeout: "120s"
  streaming_timeout: "600s"
  health_check_timeout: "30s"

# Development router settings
router:
  strategy: "round_robin"
  enable_failover: true
  max_retries: 5
  circuit_breaker_enabled: false  # Disabled for easier debugging 